; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico

[env]
lib_ldf_mode = deep+
build_unflags =
	-std=gnu++11
	-std=gnu++14
	-std=c++11
	-std=c++14
build_flags =
	-std=gnu++14
	-Wall
	-Wextra
check_tool =
	clangtidy
	cppcheck
check_skip_packages = yes
check_src_filters =
	+<lib/Luefterklappe/src/>
check_flags =
	clangtidy: --config-file=.clang-tidy
	cppcheck: --std=c++14 --enable=all --inline-suppr --suppressions-list=.cppcheck-suppressions

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
lib_deps =
	waspinator/AccelStepper@^1.64
build_src_filter =
	+<*>
	-<tmc_uart_step_dir_test.cpp>
build_flags =
	${env.build_flags}
	-Wno-ignored-qualifiers

[env:pico_tmc_uart_step_dir_test]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter =
	-<*>
	+<tmc_uart_step_dir_test.cpp>
build_flags =
	${env.build_flags}
	-Wno-ignored-qualifiers

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_flags =
	${env.build_flags}
	-DUNIT_TEST
	-Wpedantic
	-Wconversion
	-Wshadow
	-Wno-sign-conversion
